//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/Flappy/InputsFlappy/FlappyInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @FlappyInputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @FlappyInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""FlappyInputs"",
    ""maps"": [
        {
            ""name"": ""FlappyController"",
            ""id"": ""a43d61a4-f818-44e3-8b87-79250029c808"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""514e9741-7306-4531-83d6-22dedca0bbc1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ee9c9130-e4ef-46a5-9253-b407b32ed862"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // FlappyController
        m_FlappyController = asset.FindActionMap("FlappyController", throwIfNotFound: true);
        m_FlappyController_Jump = m_FlappyController.FindAction("Jump", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // FlappyController
    private readonly InputActionMap m_FlappyController;
    private IFlappyControllerActions m_FlappyControllerActionsCallbackInterface;
    private readonly InputAction m_FlappyController_Jump;
    public struct FlappyControllerActions
    {
        private @FlappyInputs m_Wrapper;
        public FlappyControllerActions(@FlappyInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_FlappyController_Jump;
        public InputActionMap Get() { return m_Wrapper.m_FlappyController; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FlappyControllerActions set) { return set.Get(); }
        public void SetCallbacks(IFlappyControllerActions instance)
        {
            if (m_Wrapper.m_FlappyControllerActionsCallbackInterface != null)
            {
                @Jump.started -= m_Wrapper.m_FlappyControllerActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_FlappyControllerActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_FlappyControllerActionsCallbackInterface.OnJump;
            }
            m_Wrapper.m_FlappyControllerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
            }
        }
    }
    public FlappyControllerActions @FlappyController => new FlappyControllerActions(this);
    public interface IFlappyControllerActions
    {
        void OnJump(InputAction.CallbackContext context);
    }
}
